// <auto-generated />
using System;
using AcaiUds.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AcaiUds.Migrations
{
    [DbContext(typeof(ContextoAcai))]
    partial class ContextoAcaiModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AcaiUds.Model.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("AcaiUds.Model.Sabores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Sabores");
                });

            modelBuilder.Entity("AcaiUds.Model.Tamanho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescricaoItem");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int?>("SaborId");

                    b.Property<int>("TempoPreparo");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("SaborId");

                    b.ToTable("Tamanho");
                });

            modelBuilder.Entity("AcaiUds.Model.Tamanho", b =>
                {
                    b.HasOne("AcaiUds.Model.Sabores", "Sabor")
                        .WithMany()
                        .HasForeignKey("SaborId");
                });
#pragma warning restore 612, 618
        }
    }
}
